functional:
  - У пользователя должен быть личный кабинет. Тест 1
  - Для входа в аккаунт логин и пароль должны быть корректны Тест 2, 3, 4, 5, 
  - Зарегистрированный пользователь может восстановить забытый пароль по email Тест 6
  - Пользователь может войти без регистрации на сайт, используя аккаунт Discord Тест 7
  - Пользователь может войти без регистрации на сайт, используя аккаунт Github Тест 8
  - Пароль должен содержать не менее 6 символов русского, английского языка или спецсимволов. Тест 9
  - У пользователя должен быть уникальный Nickname. Тест 10
  - При регистрации у пользователя должен быть корректный email. Тест 11
  - При регистрации у пользователя должно быть имя длиной не менее 3 символов. Тест 12
  - Нельзя зарегистировать двух пользователей с одним email. Тест 13
  - Пользователь может создавать игру. Тест 14
  - Пользователь может изменять настройки в разделе создания игры Тест 15
  - Пользователь может выбирать уровень при создании игры Тест 16
  - Пользователю доступны 4 уровня игры. Тест 17
  - Пользователь может выбирать "Game type" при создании игры. Тест 18
  - Пользователю доступн "Game type" - "with a bot" Тест 19
  - Пользователю доступен "Game type" - "with a friend" (по ссылке-приглашении) Тест 20
  - Пользователю доступен "Game type" - "with other users" Тест 21
  - Пользователю доступен выбор количества времени "Time control" при создании игры Тест 22
  - Пользователю доступен "Time control" от 3 до 60 минут.
  - Пользователю доступен выбор задания по названию "name".
  - Пользователю доступен выбор задания по тегам "tags". 
  - Два пользователя (игрока) должны иметь возможность соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Пользователь может принять приглашение в игру от другого авторизированного пользователя. 
  - Пользователь может отклонить приглашение в игру от другого авторизированного пользователя.
  - Каждый пользователь участвует в рейтинге (недельном, месячном, за весь период существования сайта).
  - SPA приложение
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - у пользователя должен быть личный кабинет
  - Пользователи могут общаться с соперниками и другими пользователями
  - Пользователь может наблюдать за чужими играми
  - Сайтом можно пользоваться на двух языках - русский и английский
