functional:
  - Два пользователя (игрока) должны иметь возможность соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Каждый пользователь участвует в рейтинге (недельном, месячном, за весь период существования сайта).
  - Пользователь должен иметь возможность играть с ботом
  - Пользователь должен иметь возможность играть с другом по средством ссылки
  - SPA приложение
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - у пользователя должен быть личный кабинет
  - Пользователи могут общаться с соперниками и другими пользователями
