functional:
  - У пользователя должен быть личный кабинет
  - Для входа в аккаунт логин и пароль должны быть корректны
  - Зарегистрированный пользователь может восстановить забытый пароль по email
  - Пользователь может войти без регистрации на сайт, используя аккаунт Discord
  - Пользователь может войти без регистрации на сайт, используя аккаунт Github
  - Пароль должен содержать не менее 6 символов русского, английского языка или спецсимволов
  - У пользователя должен быть уникальный Nickname
  - При регистрации у пользователя должен быть корректный email
  - При регистрации у пользователя должно быть имя длиной не менее 3 символов
  - Нельзя зарегистировать двух пользователей с одним email
  - Пользователь может создавать игру
  - Пользователь может изменять настройки в разделе создания игры
  - Пользователь может выб  ирать "level" при создании игры
  - Пользователю доступны 4 уровня игры.
  - Пользователь может выбирать "Game type" при создании игры
  - Пользователю доступен "Game type" - "with other users"
  - Пользователю доступен "Game type" - "with a friend" (по ссылке-приглашении)
  - Пользователю доступна поисковая строка "Choose opponent" при создании игры с "Game type"
  - Пользователю доступн "Game type" - "with a bot"
  - Пользователю доступен выбор количества времени "Time control" при создании игры
  - Пользователю доступен "Time control" от 3 до 60 минут.
  - Пользователю доступен выбор задания по названию "name".
  - Пользователю доступен выбор задания по тегам "tags". 
  - Два пользователя (игрока) должны иметь возможность соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Пользователь может принять приглашение в игру от другого авторизированного пользователя. 
  - Пользователь может отклонить приглашение в игру от другого авторизированного пользователя.
  - Каждый пользователь участвует в рейтинге (недельном, месячном, за весь период существования сайта).
  - SPA приложение
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
  - у пользователя должен быть личный кабинет
  - Пользователи могут общаться с соперниками и другими пользователями
  - Пользователь может наблюдать за чужими играми
  - Сайтом можно пользоваться на двух языках - русский и английский
